# Generated by Django 5.1.3 on 2025-04-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="click_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
